### ISSUE TITLE
do SEO

### ISSUE THREAD

**Issue by bodyflex** [Kanttiinit/web#6]

**Comment by mikylucky** [comment]
Just made a pull request for Facebook Open Graph optimization
https://github.com/Kanttiinit/web/pull/35

**Comment by mikylucky** [comment]
Can you write me a 150 charachters long description for the website description meta?

**Comment by bodyflex** [comment]
would this be too short "Kanttiinit.fi näyttää kätevästi Otaniemen sekä Helsingin opiskelijaruokaloiden ruokalistat."?

**Comment by mikylucky** [comment]
It's 90 chars, try to explain more about the app. It goes in the SERP under the title, so the most explainatory it is, the more people will click

**Comment by bodyflex** [comment]
"Kanttiinit.fi näyttää kätevästi Otaniemen sekä Helsingin opiskelijaruokaloiden ruokalistat. Kanttiinien avulla voit katsoa ruokalistat mobiilisovelluksella, Telegram-botilla tai suoraan selaimellasi."

**Comment by mikylucky** [comment]
Great
