### ISSUE TITLE
Request for API/Data Access for a Student Project

### ISSUE THREAD

**Issue by xfcced** [Kanttiinit/web#72]
Hi, I'm a chinese "fuksis" of Aalto University this year. 

I would like to build a new non-commercial canteen website based on your data and interfaces(like /menus or /restraunts) and I'm wondering if you would kindly authorize me to access these data. I noticed that your projects are hosted with a GPL license, but it only contains the code, not the data.

I must admit that my English is not perfect, so when I first came here, I had trouble understanding the menus. One reason is that we have quite different name pattern regarding to dish names. More importantly, in China, we have popular review&comment apps where people can check the picture of the dishes, and leave comments. It is a more direct way for Chinese people to know if the dish is good or not by checking all the reviews and pictures.

Due to that, my typicall use case of the current kanttiinit website is translating some interesting dishes to chinese, then searching them on Google to see actual pictures. Some other students may even ask for recommendations and food reviews everyday in WeChat group chat (just in case you’re not familiar with it, it’s a chinese version of Telegram, nearly every chinese use that for messaging).

If you grant me the data, the two main features I plan to implement will be corresponding to issues mentioned before. First, adding localized chinses translation on each dish, then creating a review system that everyone can upload their thoughts and feedback.

To clarify, I will make this project as a fully open-source and non-commercial one. My goal is to have some fun while gaining practical experiences on software developing skills. And if it turns out to be really helpful to others, I’ll be more pleased.

Looking forward to your response! (I also sent a message through the "contact" on the kanttiinit website, if you already saw that, please close this issue, sorry to bother.)

**Comment by IiroP** [comment]
The API can be found at [Kitchen](https://github.com/Kanttiinit/kitchen) repo, it's publicly accessible at [https://kitchen.kanttiinit.fi/](https://kitchen.kanttiinit.fi/).
